version: '3'

services:
  timescaledb:
    image: timescale/timescaledb:2.20.0-pg17
    ports:
      - "30000:5432"  # Expose PostgreSQL (TimescaleDB) on host port 30000
    environment:
      POSTGRES_PASSWORD: password  # Default POSTGRES_USER: postgres, Default POSTGRES_DB: postgres
    volumes:
      - ./data/timescale:/var/lib/postgresql/data  # Host-relative path for TimescaleDB data
    restart: unless-stopped

  grafana:
    image: grafana/grafana-oss
    ports:
      - "30001:3000"  # Expose Grafana web UI on host port 30001
    depends_on:
      - timescaledb
    volumes:
      - ./data/grafana:/var/lib/grafana  # Host-relative path for Grafana data
    restart: unless-stopped

  nodered:
    image: nodered/node-red
    ports:
      - "30002:1880"  # Expose Node-RED web UI on host port 1880
    volumes:
      - ./data/nodered:/data  # Host-relative path for Node-RED data
    restart: unless-stopped